### ISSUE TITLE
No Tailwind styling on form validation elements.

### ISSUE THREAD

**Issue by HaresMahmood** [HaresMahmood/orientation-hackathon#12]
# Overview
Tailwind classes do not style form validation text properly,

## Reproduction steps
1. Navigate to the [profile page](http://localhost:3000/profile).
3. Ensure at least one required field is left unpopulated.
4. Press the `Save changes` button.
5. Observe default styling for form validation elements (*Required* text next to `input` element).

# Documentation

## Screenshots

![image](https://user-images.githubusercontent.com/14112766/172057979-b2282590-3a89-4be6-92c6-0774cface576.png)

**Comment by hreyesm** [comment]
Forgot to close this issue yesterday. Fixed it by adding `'./features/**/*.{js,ts,jsx,tsx}'` to `tailwind.config.js` as part of the same PR (see commit https://github.com/HaresMahmood/orientation-hackathon/commit/617e7562d8eb045c3d8e3c2b10a87d885f885dea).
