### ISSUE TITLE
Identical `id`s and `name`s of certain `input` fields.

### ISSUE THREAD

**Issue by HaresMahmood** [HaresMahmood/orientation-hackathon#6]
# Overview
The `id`s and `name`s of date pickers on the profile-page are identical. This is currently the case because there will be several sub-categories for `Education` and `Work Experience` - the `id` 

## Reproduction steps
*N/A*

**Comment by hreyesm** [comment]
Fixed input `id` and `name` overlap in PR #11. Input data is now semantically correct and fully accessible from the form handler.
