### ISSUE TITLE
Certain form categories overflow on mobile.

### ISSUE THREAD

**Issue by HaresMahmood** [HaresMahmood/orientation-hackathon#8]
# Overview
When navigating to the profile-page while viewing the page on mobile, certain `div` elements representing form categories overflow the page. 

## Reproduction steps
1. Ensure the screen size of the device being used is smaller than `695 px` wide.
2.  Navigate to the [profile page](http://localhost:3000/profile).
3. Observe the `Education` and `Work Experience` categories overflowing the page.

# Fixes

This happens due to date picker containers not being responsive and having a rigid size. They should instead use Flexbox and be collapsed on smaller screens.

# Documentation

## Screenshots

![image](https://user-images.githubusercontent.com/14112766/171941768-4843ec83-310e-46c0-ac8a-6312310d9272.png)

**Comment by hreyesm** [comment]
Still having this issue.
